# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iriverui.ui'
#
# Created: Mon Aug 11 12:47:38 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Tuner(object):
    def setupUi(self, Tuner):
        Tuner.setObjectName(_fromUtf8("Tuner"))
        Tuner.setEnabled(True)
        Tuner.resize(270, 660)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tuner.sizePolicy().hasHeightForWidth())
        Tuner.setSizePolicy(sizePolicy)
        Tuner.setMinimumSize(QtCore.QSize(270, 660))
        Tuner.setMaximumSize(QtCore.QSize(270, 660))
        self.stationsList = QtGui.QTableWidget(Tuner)
        self.stationsList.setGeometry(QtCore.QRect(10, 190, 250, 366))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationsList.sizePolicy().hasHeightForWidth())
        self.stationsList.setSizePolicy(sizePolicy)
        self.stationsList.setAutoFillBackground(False)
        self.stationsList.setAlternatingRowColors(True)
        self.stationsList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.stationsList.setShowGrid(True)
        self.stationsList.setGridStyle(QtCore.Qt.SolidLine)
        self.stationsList.setCornerButtonEnabled(True)
        self.stationsList.setObjectName(_fromUtf8("stationsList"))
        self.stationsList.setColumnCount(2)
        self.stationsList.setRowCount(20)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.stationsList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(17, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(17, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(18, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(18, 1, item)
        item = QtGui.QTableWidgetItem()
        self.stationsList.setItem(19, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stationsList.setItem(19, 1, item)
        self.stationsList.horizontalHeader().setVisible(True)
        self.stationsList.horizontalHeader().setCascadingSectionResizes(False)
        self.stationsList.horizontalHeader().setHighlightSections(False)
        self.stationsList.horizontalHeader().setSortIndicatorShown(False)
        self.stationsList.horizontalHeader().setStretchLastSection(True)
        self.stationsList.verticalHeader().setDefaultSectionSize(17)
        self.stationsList.verticalHeader().setHighlightSections(False)
        self.stationsList.verticalHeader().setMinimumSectionSize(17)
        self.stationsList.verticalHeader().setSortIndicatorShown(False)
        self.stationsList.verticalHeader().setStretchLastSection(False)
        self.iriverLogo = QtGui.QLabel(Tuner)
        self.iriverLogo.setGeometry(QtCore.QRect(10, 10, 250, 97))
        self.iriverLogo.setStatusTip(_fromUtf8(""))
        self.iriverLogo.setText(_fromUtf8(""))
        self.iriverLogo.setPixmap(QtGui.QPixmap(_fromUtf8("app/iRiver_250.png")))
        self.iriverLogo.setObjectName(_fromUtf8("iriverLogo"))
        self.groupBox = QtGui.QGroupBox(Tuner)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 250, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioUSA = QtGui.QRadioButton(self.groupBox)
        self.radioUSA.setGeometry(QtCore.QRect(10, 20, 181, 21))
        self.radioUSA.setObjectName(_fromUtf8("radioUSA"))
        self.radioJapan = QtGui.QRadioButton(self.groupBox)
        self.radioJapan.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.radioJapan.setObjectName(_fromUtf8("radioJapan"))
        self.radioEurope = QtGui.QRadioButton(self.groupBox)
        self.radioEurope.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.radioEurope.setObjectName(_fromUtf8("radioEurope"))
        self.verticalLayoutWidget = QtGui.QWidget(Tuner)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 590, 251, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.loadButton.setStyleSheet(_fromUtf8("border:1px solid #ddd;"))
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setStyleSheet(_fromUtf8("border:1px solid #ddd;"))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.exitButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.exitButton.setStyleSheet(_fromUtf8("border:1px solid #ddd;"))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.verticalLayout.addWidget(self.exitButton)
        self.author = QtGui.QLabel(Tuner)
        self.author.setGeometry(QtCore.QRect(10, 570, 251, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.author.setFont(font)
        self.author.setToolTip(_fromUtf8(""))
        self.author.setStatusTip(_fromUtf8(""))
        self.author.setAlignment(QtCore.Qt.AlignCenter)
        self.author.setObjectName(_fromUtf8("author"))

        self.retranslateUi(Tuner)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Tuner.close)
        QtCore.QMetaObject.connectSlotsByName(Tuner)

    def retranslateUi(self, Tuner):
        Tuner.setWindowTitle(_translate("Tuner", "iRiver Tuner Settings", None))
        item = self.stationsList.verticalHeaderItem(0)
        item.setText(_translate("Tuner", "1", None))
        item = self.stationsList.verticalHeaderItem(1)
        item.setText(_translate("Tuner", "2", None))
        item = self.stationsList.verticalHeaderItem(2)
        item.setText(_translate("Tuner", "3", None))
        item = self.stationsList.verticalHeaderItem(3)
        item.setText(_translate("Tuner", "4", None))
        item = self.stationsList.verticalHeaderItem(4)
        item.setText(_translate("Tuner", "5", None))
        item = self.stationsList.verticalHeaderItem(5)
        item.setText(_translate("Tuner", "6", None))
        item = self.stationsList.verticalHeaderItem(6)
        item.setText(_translate("Tuner", "7", None))
        item = self.stationsList.verticalHeaderItem(7)
        item.setText(_translate("Tuner", "8", None))
        item = self.stationsList.verticalHeaderItem(8)
        item.setText(_translate("Tuner", "9", None))
        item = self.stationsList.verticalHeaderItem(9)
        item.setText(_translate("Tuner", "10", None))
        item = self.stationsList.verticalHeaderItem(10)
        item.setText(_translate("Tuner", "11", None))
        item = self.stationsList.verticalHeaderItem(11)
        item.setText(_translate("Tuner", "12", None))
        item = self.stationsList.verticalHeaderItem(12)
        item.setText(_translate("Tuner", "13", None))
        item = self.stationsList.verticalHeaderItem(13)
        item.setText(_translate("Tuner", "14", None))
        item = self.stationsList.verticalHeaderItem(14)
        item.setText(_translate("Tuner", "15", None))
        item = self.stationsList.verticalHeaderItem(15)
        item.setText(_translate("Tuner", "16", None))
        item = self.stationsList.verticalHeaderItem(16)
        item.setText(_translate("Tuner", "17", None))
        item = self.stationsList.verticalHeaderItem(17)
        item.setText(_translate("Tuner", "18", None))
        item = self.stationsList.verticalHeaderItem(18)
        item.setText(_translate("Tuner", "19", None))
        item = self.stationsList.verticalHeaderItem(19)
        item.setText(_translate("Tuner", "20", None))
        item = self.stationsList.horizontalHeaderItem(0)
        item.setText(_translate("Tuner", "Nazwa", None))
        item = self.stationsList.horizontalHeaderItem(1)
        item.setText(_translate("Tuner", "MHz", None))
        __sortingEnabled = self.stationsList.isSortingEnabled()
        self.stationsList.setSortingEnabled(False)
        self.stationsList.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Tuner", "Region", None))
        self.radioUSA.setText(_translate("Tuner", "USA/Korea (87-108 MHz)", None))
        self.radioJapan.setText(_translate("Tuner", "Japonia (76-90 MHz)", None))
        self.radioEurope.setText(_translate("Tuner", "Europa (87-108 MHz)", None))
        self.loadButton.setText(_translate("Tuner", "&Wczytaj plik", None))
        self.saveButton.setText(_translate("Tuner", "Zapi&sz plik", None))
        self.exitButton.setText(_translate("Tuner", "&Zamknij", None))
        self.author.setText(_translate("Tuner", "Autor: K.S. © 2014", None))

